package goxsd9_test

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/goxdra/goxsd9"
)

const libraryExampleSchema = `<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:example" targetNamespace="urn:example">
  <xs:simpleType name="Amount"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2"/></xs:restriction></xs:simpleType>
  <xs:element name="price" type="t:Amount"/>
</xs:schema>`

const libraryExampleInstance = `<price xmlns="urn:example">12.50</price>`

func Example() {
	root, err := newLibraryExampleRoot()
	if err != nil {
		reportLibraryExampleError("NewResolvedSource", err)
		return
	}

	schema, err := goxsd9.ParseSchema(root, nil)
	if err != nil {
		reportLibraryExampleError("ParseSchema", err)
		return
	}
	components := schema.Components()
	if len(components) != 2 {
		reportLibraryExampleError("unexpected schema component count", fmt.Errorf("got %d, want 2", len(components)))
		return
	}

	instanceReader := io.NopCloser(strings.NewReader(libraryExampleInstance))
	err = goxsd9.ValidateInstance(schema, "price.xml", instanceReader)
	if err != nil {
		reportLibraryExampleError("ValidateInstance", err)
		return
	}

	// generated is the complete formatted source returned by the public API.
	generated, err := goxsd9.GenerateGo(schema, "generated")
	if err != nil {
		reportLibraryExampleError("GenerateGo", err)
		return
	}
	repeated, err := goxsd9.GenerateGo(schema, "generated")
	if err != nil {
		reportLibraryExampleError("GenerateGo second", err)
		return
	}
	if !bytes.Equal(generated, repeated) {
		reportLibraryExampleError("GenerateGo output", errors.New("is not deterministic"))
		return
	}
	if len(generated) == 0 {
		reportLibraryExampleError("GenerateGo output", errors.New("is empty"))
		return
	}

	formatted, err := format.Source(generated)
	if err != nil {
		reportLibraryExampleError("format.Source", err)
		return
	}
	if !bytes.Equal(generated, formatted) {
		reportLibraryExampleError("format.Source", errors.New("changed generated bytes"))
		return
	}
	if err := compileLibraryExampleSource(generated); err != nil {
		reportLibraryExampleError("compile generated source", err)
		return
	}

	if err := writeLibraryExampleOutput(len(components)); err != nil {
		return
	}
	// Output:
	// schema components: 2
	// instance: valid text-only price
	// generated Go: complete source is formatted, deterministic, and externally compilable
}

func newLibraryExampleRoot() (goxsd9.ResolvedSource, error) {
	schemaReader := io.NopCloser(strings.NewReader(libraryExampleSchema))
	root, err := goxsd9.NewResolvedSource(context.Background(), "quickstart.xsd", schemaReader)
	if err == nil {
		return root, nil
	}
	closeErr := schemaReader.Close()
	if closeErr != nil {
		return goxsd9.ResolvedSource{}, errors.Join(err, fmt.Errorf("close schema reader: %w", closeErr))
	}
	return goxsd9.ResolvedSource{}, err
}

func reportLibraryExampleError(label string, err error) {
	if printErr := writeLibraryExampleLine(label+":", err); printErr != nil {
		return
	}
}

func writeLibraryExampleLine(args ...any) error {
	_, err := fmt.Println(args...)
	return err
}

func writeLibraryExampleOutput(componentCount int) error {
	if err := writeLibraryExampleLine("schema components:", componentCount); err != nil {
		return err
	}
	if err := writeLibraryExampleLine("instance: valid text-only price"); err != nil {
		return err
	}
	return writeLibraryExampleLine("generated Go: complete source is formatted, deterministic, and externally compilable")
}

// compileLibraryExampleSource writes the complete generated source unchanged before compiling it externally.
func compileLibraryExampleSource(source []byte) (err error) {
	moduleRoot, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("get module root: %w", err)
	}
	temporary, err := os.MkdirTemp("", "goxsd9-library-example-")
	if err != nil {
		return fmt.Errorf("create temporary consumer module: %w", err)
	}
	defer func() {
		if removeErr := os.RemoveAll(temporary); removeErr != nil {
			err = errors.Join(err, fmt.Errorf("remove temporary consumer module: %w", removeErr))
		}
	}()

	goMod := fmt.Sprintf("module generated.test\n\ngo 1.26.0\n\nrequire github.com/goxdra/goxsd9 v0.0.0\n\nreplace github.com/goxdra/goxsd9 => %s\n", moduleRoot)
	err = os.WriteFile(filepath.Join(temporary, "go.mod"), []byte(goMod), 0o600)
	if err != nil {
		return fmt.Errorf("write consumer go.mod: %w", err)
	}
	err = os.WriteFile(filepath.Join(temporary, "generated.go"), source, 0o600)
	if err != nil {
		return fmt.Errorf("write generated source: %w", err)
	}

	command := exec.CommandContext(context.Background(), "go", "test", "./...")
	command.Dir = temporary
	command.Env = append(os.Environ(), "GOWORK=off")
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("go test consumer module: %w\n%s", err, output)
	}
	return nil
}
